services:
     - type: web
       name: markdown-processor
       env: docker
       dockerfilePath: ./Dockerfile
       envVars:
         - key: GOOGLE_APPLICATION_CREDENTIALS
           sync: false
       healthCheckPath: /
       numInstances: 1
       plan: free